package me.petulikan1.zMachines.utils;


import lombok.Getter;
import lombok.NonNull;
import me.petulikan1.zMachines.Loader;
import me.petulikan1.zMachines.config.Config;

import java.io.File;
import java.math.BigDecimal;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

public class SQLAPI {
    private final String host;
    private final String database;
    private final String username;
    private final String password;
    private final int port;
    private final Type type;
    @Getter
    private Connection connection;
    private String at = "?useSSL=false&useUnicode=true&characterEncoding=utf8";

    public SQLAPI(String host, String database, String username, String password, int port, Type type) {
        this.host = host;
        this.database = database;
        this.username = username;
        this.password = password;
        this.port = port;
        this.type = type;
    }

    public enum Type {
        MYSQL,
        SQLITE;

        public static Type fromString(String a) {
            for (Type t : Type.values()) {
                if (t.name().equalsIgnoreCase(a))
                    return t;
            }
            return null;
        }

    }

    public static SQLAPI create(String path, Config c, Type type) throws Exception {
        String host = c.getString(path + ".Host");
        String database = c.getString(path + ".Database");
        String username = c.getString(path + ".Username");
        String password = c.getString(path + ".Password");
        int port = c.getInt(path + ".Port");
        Validator.validate(host == null || host.isEmpty(), "MySqlStorageHandler > Host cannot be null or empty");
        Validator.validate(username == null || username.isEmpty(), "MySqlStorageHandler > Username cannot be null or empty");
        Validator.validate(database == null || database.isEmpty(), "MySqlStorageHandler > Database cannot be null or empty");
        Validator.validate(password == null || password.isEmpty(), "MySqlStorageHandler > Password cannot be null or empty");
        Validator.validate(type == null, "MySqlStorageHandler > Type cannot be null");
        SQLAPI sqlapi = new SQLAPI(host, database, username, password, port, type);
        sqlapi.connect();
        return sqlapi;
    }

    public static SQLAPI create(Type type) throws Exception {
        SQLAPI sqlapi = new SQLAPI(null, null, null, null, 0, type);
        sqlapi.connect();
        return sqlapi;
    }


    public void checkAndConnect() throws SQLException {
        if (!isConnected())
            connect();
    }

    public boolean isConnected() {
        try {
            return connection != null && !connection.isClosed() && connection.isValid(2);
        } catch (Exception ignored) {
            return false;
        }
    }

    public void close() {
        try {
            connection.close();
        } catch (Exception ignored) {
        }
        connection = null;
    }

    public boolean reconnect() throws Exception {
        close();
        return connect();
    }

    public void createTable(String table, String values) throws SQLException {
        execute("CREATE TABLE IF NOT EXISTS " + table + " (" + values + ")");
    }

    public void deleteTable(String table) throws SQLException {
        execute("DROP TABLE " + table);
    }

    public void remove(String table, String lookingfor, String identifier) throws SQLException {
        execute("DELETE FROM " + table + " WHERE " + lookingfor + "='" + identifier + "'");
    }

    public void clearTable(String table) throws SQLException {
        execute("DELETE FROM " + table);
    }

    public PreparedStatement getPreparedStatement(@NonNull String command) throws SQLException {
        checkAndConnect();
        return connection.prepareStatement(command);
    }

    public PreparedStatement getPreparedStatement(@NonNull String command, int autoGeneratedKeys) throws SQLException {
        checkAndConnect();
        return connection.prepareStatement(command, autoGeneratedKeys);
    }

    public boolean update(String command) throws SQLException {
        return update(getPreparedStatement(command));
    }

    public boolean update(PreparedStatement command) throws SQLException {
        if (command == null) return false;
        boolean result = false;
        command.executeUpdate();
        result = true;
        return result;
    }

    public boolean largeUpdate(String command) throws SQLException {
        return largeUpdate(getPreparedStatement(command));
    }

    public boolean largeUpdate(PreparedStatement command) throws SQLException {
        if (command == null) return false;
        boolean result = false;
        command.executeLargeUpdate();
        result = true;
        return result;
    }

    public ResultSet query(String command) throws SQLException {
        return query(getPreparedStatement(command));
    }

    public ResultSet query(PreparedStatement command) throws SQLException {
        if (command == null) return null;
        return command.executeQuery();
    }


    public int getInt(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getInt(lookingfor);
            return 0;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    public void insert(String table, Object... values) throws SQLException {
        String items = "";
        Object[] var7 = values;
        int var6 = values.length;
        Object command;
        for (int var5 = 0; var5 < var6; ++var5) {
            command = var7[var5];
            items = items + (command != null ? ", '" + command + "'" : ", null");
        }
        if (!items.trim().isEmpty()) {
            items = items.substring(2);
            command = "INSERT INTO " + table + " VALUES (" + items + ")";
            this.execute(command + "");
        }
    }

    public void set(String table, String path, String value, String identifier, String idValue) {
        String command = "UPDATE " + table + " SET " + path + "='" + value + "' WHERE " + identifier + "='" + idValue
                + "'";
        try {
            update(command);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public long getLong(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getLong(lookingfor);
            return 0;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    public Array getArray(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getArray(lookingfor);
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public boolean getBoolean(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getBoolean(lookingfor);
            return false;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public byte getByte(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getByte(lookingfor);
            return 0;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    public Object getObject(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getObject(lookingfor);
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public BigDecimal getBigDecimal(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getBigDecimal(lookingfor);
            return new BigDecimal(0);
        } catch (Exception e) {
            e.printStackTrace();
            return new BigDecimal(0);
        }
    }

    public double getDouble(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getDouble(lookingfor);
            return 0.0;
        } catch (Exception e) {
            e.printStackTrace();
            return 0.0;
        }
    }

    public String getString(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT * FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet s = query(command);
            if (s != null && s.next())
                return s.getString(lookingfor);
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public List<String> getStrings(String table, String lookingfor, String identifier, String idValue) {
        String command = "SELECT " + lookingfor + " FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        List<String> values = new ArrayList<>();
        try {
            ResultSet s = query(command);
            while (s != null && s.next())
                values.add(s.getString(lookingfor));
        } catch (Exception e) {
            e.printStackTrace();
        }
        return values;
    }

    public boolean exists(String table, String identifier, String idValue) {
        String command = "SELECT * FROM " + table + " WHERE " + identifier + "='" + idValue + "'";
        try {
            ResultSet q = query(command);
            return q != null && q.next();
        } catch (Exception e) {
            return false;
        }
    }

    public boolean execute(String command) throws SQLException {
        return execute(getPreparedStatement(command));
    }

    public boolean execute(PreparedStatement command) throws SQLException {
        if (command == null) return false;
        command.execute();
        return true;
    }

    public void setConnectAttributes(String attributes) {
        at = attributes;
    }

    private Properties properties;

    private Properties getProperties() {
        if (properties == null) {
            properties = new Properties();
            properties.setProperty("user", username);
            properties.setProperty("password", password);
            properties.setProperty("MaxPooledStatements", "250");
        }
        return properties;
    }

    private boolean connect() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
        return switch (type) {
            case MYSQL -> {
                Properties properties = getProperties();
                yield mysql(properties);
            }
            case SQLITE -> sqlite();
        };
    }


    private boolean sqlite() {
        try {
            Class.forName("org.sqlite.JDBC");
            File f = new File("plugins/zMachines/database.db");
            f.getParentFile().mkdirs();
            connection = DriverManager.getConnection("jdbc:sqlite:" + f);
            return true;
        } catch (Exception e) {
            Loader.main.error("Failed to connect to SQLite database! Error: " + e.getMessage());
            return false;
        }
    }

    private boolean mysql(Properties properties) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://" + host + ":" + port + "/" + database + at, properties);
            return true;
        } catch (Exception e) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                connection = DriverManager.getConnection("jdbc:mysql://" + host + ":" + port + "/" + database + at, properties);
                return true;
            } catch (Exception b) {
                Loader.main.error("Failed to connect to MySQL database! Error: " + b.getMessage());
                return false;
            }
        }
    }
}
